import '../models/draw_model.dart';
import '../models/transaction_model.dart';
import '../models/result_models.dart';

// ── Free Unsplash images (no API key needed) ──────────────
class MockData {

  static List<DrawModel> get draws => [
    DrawModel(
      id: 1,
      prizeName: 'Honda CB150F 2025',
      prizeDescription: 'Brand new Honda CB150F motorcycle in red color. Full registration, 1 year warranty included. Winner will be contacted within 48 hours.',
      prizeImageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      prizeValue: 285000,
      prizeType: 'physical',
      entryPrice: 10,
      maxEntries: 500,
      maxPerUser: 50,
      category: 'bike',
      status: 'active',
      isFeatured: true,
      endTime: DateTime.now().add(const Duration(hours: 47)),
      entriesSold: 423,
      userEntries: 0,
    ),
    DrawModel(
      id: 2,
      prizeName: 'iPhone 16 Pro Max',
      prizeDescription: 'Apple iPhone 16 Pro Max 256GB in Natural Titanium. Brand new sealed box with all accessories.',
      prizeImageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800',
      prizeValue: 180000,
      prizeType: 'physical',
      entryPrice: 5,
      maxEntries: 1000,
      maxPerUser: 100,
      category: 'phone',
      status: 'active',
      isFeatured: true,
      endTime: DateTime.now().add(const Duration(hours: 23)),
      entriesSold: 750,
      userEntries: 3,
    ),
    DrawModel(
      id: 3,
      prizeName: 'Rolex Submariner',
      prizeDescription: 'Genuine Rolex Submariner Date watch. Includes original box, papers, and 5-year service warranty.',
      prizeImageUrl: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800',
      prizeValue: 250000,
      prizeType: 'physical',
      entryPrice: 20,
      maxEntries: 300,
      maxPerUser: 30,
      category: 'watch',
      status: 'active',
      isFeatured: false,
      endTime: DateTime.now().add(const Duration(days: 3)),
      entriesSold: 180,
      userEntries: 0,
    ),
    DrawModel(
      id: 4,
      prizeName: 'MacBook Pro M3',
      prizeDescription: 'Apple MacBook Pro 14" with M3 chip, 16GB RAM, 512GB SSD. Space Gray color.',
      prizeImageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
      prizeValue: 320000,
      prizeType: 'physical',
      entryPrice: 15,
      maxEntries: 400,
      maxPerUser: 40,
      category: 'gadget',
      status: 'active',
      isFeatured: false,
      endTime: DateTime.now().add(const Duration(days: 5)),
      entriesSold: 95,
      userEntries: 0,
    ),
    DrawModel(
      id: 5,
      prizeName: 'PKR 50,000 Cash Prize',
      prizeDescription: 'Win PKR 50,000 cash directly to your JazzCash or EasyPaisa account. Instant transfer after draw.',
      prizeImageUrl: 'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?w=800',
      prizeValue: 50000,
      prizeType: 'cash',
      entryPrice: 2,
      maxEntries: 2000,
      maxPerUser: 200,
      category: 'cash',
      status: 'active',
      isFeatured: true,
      endTime: DateTime.now().add(const Duration(hours: 12)),
      entriesSold: 1850,
      userEntries: 10,
    ),
    DrawModel(
      id: 6,
      prizeName: 'Samsung Galaxy S25 Ultra',
      prizeDescription: 'Samsung Galaxy S25 Ultra 512GB in Titanium Black. Includes S-Pen and premium case.',
      prizeImageUrl: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800',
      prizeValue: 150000,
      prizeType: 'physical',
      entryPrice: 5,
      maxEntries: 800,
      maxPerUser: 80,
      category: 'phone',
      status: 'active',
      isFeatured: false,
      endTime: DateTime.now().add(const Duration(days: 2)),
      entriesSold: 320,
      userEntries: 0,
    ),
    DrawModel(
      id: 7,
      prizeName: 'Yamaha YBR 125G',
      prizeDescription: 'Brand new Yamaha YBR 125G motorcycle. Full registration included. Available in black or red.',
      prizeImageUrl: 'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=800',
      prizeValue: 160000,
      prizeType: 'physical',
      entryPrice: 8,
      maxEntries: 600,
      maxPerUser: 60,
      category: 'bike',
      status: 'active',
      isFeatured: false,
      endTime: DateTime.now().add(const Duration(days: 4)),
      entriesSold: 210,
      userEntries: 0,
    ),
    DrawModel(
      id: 8,
      prizeName: 'Sony PlayStation 5',
      prizeDescription: 'Sony PlayStation 5 console with two DualSense controllers and 3 top games included.',
      prizeImageUrl: 'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800',
      prizeValue: 95000,
      prizeType: 'physical',
      entryPrice: 3,
      maxEntries: 1500,
      maxPerUser: 150,
      category: 'gadget',
      status: 'active',
      isFeatured: false,
      endTime: DateTime.now().add(const Duration(days: 1)),
      entriesSold: 890,
      userEntries: 5,
    ),
  ];

  static List<Transaction> get transactions => [
    Transaction(id: 1, type: TransactionType.welcomeBonus, amount: 5,
      description: 'Welcome bonus — thanks for joining!',
      status: 'completed', createdAt: DateTime.now().subtract(const Duration(days: 1))),
    Transaction(id: 2, type: TransactionType.deposit, amount: 100,
      description: 'JazzCash deposit',
      status: 'completed', createdAt: DateTime.now().subtract(const Duration(hours: 20))),
    Transaction(id: 3, type: TransactionType.entryFee, amount: -15,
      description: '3 entries in iPhone 16 Pro Max draw',
      status: 'completed', createdAt: DateTime.now().subtract(const Duration(hours: 18))),
    Transaction(id: 4, type: TransactionType.entryFee, amount: -20,
      description: '10 entries in PKR 50,000 Cash Prize draw',
      status: 'completed', createdAt: DateTime.now().subtract(const Duration(hours: 10))),
    Transaction(id: 5, type: TransactionType.referralBonus, amount: 2,
      description: 'Referral bonus — friend joined!',
      status: 'completed', createdAt: DateTime.now().subtract(const Duration(hours: 5))),
  ];

  static ReferralStats get referralStats => ReferralStats(
    totalReferrals: 3,
    activeReferrals: 2,
    totalEarned: 6,
    referralCode: 'FAHAD2025',
    leaderboard: [
      {'name': 'Ahmed K.', 'city': 'Karachi', 'referral_count': 24},
      {'name': 'Sara M.', 'city': 'Lahore', 'referral_count': 18},
      {'name': 'Usman A.', 'city': 'Islamabad', 'referral_count': 15},
      {'name': 'Fatima R.', 'city': 'Peshawar', 'referral_count': 12},
      {'name': 'Ali H.', 'city': 'Quetta', 'referral_count': 9},
    ],
  );

  static Map<String, dynamic> get currentUser => {
    'id': 1,
    'name': 'Fahad',
    'phone': '03001234567',
    'city': 'Lahore',
    'walletBalance': 72.0,
    'referralCode': 'FAHAD2025',
    'isVerified': false,
  };

  static List<SkillQuestion> get skillQuestions => [
    SkillQuestion(id: 1, question: 'What is 15 × 8?',
      optionA: '100', optionB: '120', optionC: '110', optionD: '130'),
    SkillQuestion(id: 2, question: 'Capital of Pakistan?',
      optionA: 'Lahore', optionB: 'Karachi', optionC: 'Islamabad', optionD: 'Peshawar'),
    SkillQuestion(id: 3, question: 'What is 50% of 200?',
      optionA: '50', optionB: '75', optionC: '100', optionD: '125'),
    SkillQuestion(id: 4, question: 'How many months in a year?',
      optionA: '10', optionB: '11', optionC: '12', optionD: '13'),
    SkillQuestion(id: 5, question: 'What is 9 × 9?',
      optionA: '72', optionB: '81', optionC: '91', optionD: '80'),
  ];

  // Correct answers (server-side only in production)
  static Map<int, String> get correctAnswers => {
    1: 'b', 2: 'c', 3: 'c', 4: 'c', 5: 'b',
  };
}
